# Generated by Django 3.2.3 on 2021-07-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pets_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
